# A PodSpec for the MongoDB that works with PayStubs app.

apiVersion: v1
kind: Pod
metadata:
  name: mongo
  namespace: utils-dev
  labels:
    app: paystubs
spec:
  volumes:
    - name: paystubs-storage
      persistentVolumeClaim:
        claimName: paystub-pv-claim 
  containers:
    - name: mongo1
      image: localhost:32000/utils/mongo:registry
      ports: 
        - containerPort: 27017
      volumeMounts:
        - mountPath: "/data"
          name: paystubs-storage
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongo-user-pass
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-user-pass
              key: password
      resources: 
        limits:
          cpu: 1
          memory: "500Mi"
        requests:
          cpu: 1
          memory: "200Mi"
      args: ["--auth"]
